Adding additional config/utility.
55Honey/Acore_LevelUpReward pull request #2
Opened 2021-05-13 10:57 UTC by Ragundah

Modified header to be cleaner.
Modified config layout.
Added following config options:
- Config_mailStationary
- Config_maxGMRank
- Config_preventReturn
- Config_charactersDbName
Renamed senderGUID to Config_senderGUID
Added function PreventReturn(playerGUID)
Tested and confirmed viability and functionality of additions and modifications.

2021-05-13 11:06 UTC, 55Honey requested changes
I like the additional config flag options, but if you want to change the header besides adding your name, you need to do that in your fork.

2021-05-13 11:09 UTC, Ragundah commented
Corrected and added name and update date under original header.

2021-05-13 11:17 UTC, 55Honey requested changes

2021-05-13 11:17 UTC, 55Honey commented on LevelUpReward.lua
> +local Config_mailText = 1           -- Which text to send in the mail to the player.
I want the default config to stay, so this needs to be 2

2021-05-13 11:17 UTC, 55Honey commented on LevelUpReward.lua
> +local Config_mailStationery = 61    -- Stationary used in the mail sent to the player. (41 Normal Mail, 61 GM/Blizzard Support, 62 Auction, 64 Valentines, 65 Christmas) Note: Use 62, 64, and 65 At yo
same as above, must be 41 for the "Create a permanent copy of the letter" to work

2021-05-13 11:24 UTC, Ragundah commented
Dont merge yet. An issue cropped up relating to crashing.
=

2021-05-13 11:59 UTC, Ragundah commented
Ready for any additional feedback/review as well as testing. Crash has been fixed. 62 64 and 65 stationary NOT linked to crashing it seems, but modifies the stationary in a way that could be undesirable. Leaving the text Note: Use 62, 64, and 65 At your own risk. for this reason.

2021-05-15 08:57 UTC, 55Honey requested changes
Else looks good. I'll test it today.

2021-05-15 08:57 UTC, 55Honey commented on LevelUpReward.lua
> +RegisterPlayerEvent(PLAYER_EVENT_ON_LEVEL_CHANGE, GrantReward)
missing new line.

2021-05-15 09:58 UTC, merged